defaults:
  - env: walker2d_medium_expert # Look in env for different environment choices
  - _self_

seed: 0
device_id: 0 

# Training Loop Parameters
num_epochs: 2000
num_steps_per_epoch: 1000
batch_size: 1024
eval_freq: 50
eval_episodes: 10
save_best_model: true
reward_tune: 'no'

agent:
  # RL params
  discount: 0.99
  tau: 0.005
  eta: 1.0

  # Optimizer/scheduler params
  lr: 3e-4
  critic_lr: 3e-4
  critic_weight_decay: 1e-4
  lr_decay: false
  lr_maxt: ${num_epochs}
  grad_norm: 5.0

  # Diffusion params
  beta_schedule: 'vp'
  n_timesteps: 5

  # Critic params
  max_q_backup: false

  # EMA params
  ema_decay: 0.995
  step_start_ema: 1000
  update_ema_every: 5


hydra:
  run:
    dir: results/${env.filename}-${seed}